# Process tool call
process_tc() {
    local chat_id="$1"
    local msg_id="$2"
    local tc_json="$3" # Single tool call object
    local thread_id="$4"
    
    local name=$(echo "$tc_json" | jq -r '.name')
    local args=$(echo "$tc_json" | jq -c '.args')
    
    # 1. Guardrail: Detect loops (same tool + same args in same turn)
    local args_hash=$(echo "$args" | sha256sum | awk '{print $1}')
    local call_sig="${name}_${args_hash}"
    
    # We use a turn-scoped variable to track calls
    # TURN_CALLS is initialized in run_agent
    if [[ "$TURN_CALLS" == *"$call_sig"* ]]; then
        echo "Error: Loop detected! You already called $name with these exact arguments in this turn. Change your strategy."
        return
    fi
    TURN_CALLS="$TURN_CALLS $call_sig"

    # Update Telegram status
    tg_edit "$chat_id" "$msg_id" "⚒ Running tool: \`$name\`..."
    
    log_tool_usage "$chat_id" "$name"
    local output=$(run_tool "$name" "$args" "$chat_id" "$thread_id")
    
    # Check for image attachment
    if echo "$output" | grep -q "IMAGE_URL:"; then
        local img_url=$(echo "$output" | grep "IMAGE_URL:" | head -n1 | sed 's/IMAGE_URL: //')
        tg_send_photo "$chat_id" "$img_url" "Generated by $name"
        # Remove the protocol line from output to keep history clean
        output=$(echo "$output" | grep -v "IMAGE_URL:")
    fi

    # Return output
    echo "$output"
}
