# Process tool call
process_tc() {
    local chat_id="$1"
    local msg_id="$2"
    local tc_json="$3" # Single tool call object
    local thread_id="$4"
    
    # Parse tool name and arguments using Python for robust handling
    local py_out
    py_out=$(python3 -c '
import sys, json
try:
    tc = json.loads(sys.argv[1])
    name = tc.get("function", {}).get("name") or tc.get("name", "")
    args = tc.get("function", {}).get("arguments") or tc.get("args", "{}")
    if isinstance(args, str):
        try:
            # check if it is valid json string
            json.loads(args)
        except:
            args = "{}"
    else:
        args = json.dumps(args)
        
    print(f"NAME={name.strip()}")
    print(f"ARGS={args}")
except Exception as e:
    print("NAME=unknown_tool")
    print("ARGS={}")
' "$tc_json")

    local name=$(echo "$py_out" | grep "^NAME=" | cut -d= -f2-)
    local args=$(echo "$py_out" | grep "^ARGS=" | cut -d= -f2-)
    
    if [[ -z "$name" || "$name" == "unknown_tool" ]]; then
        echo "Error: Tool name could not be parsed from JSON."
        return
    fi
    
    # 1. Guardrail: Detect loops (same tool + same args in same turn)
    local args_hash=$(echo "$args" | sha256sum | awk '{print $1}')
    local call_sig="${name}_${args_hash}"

    # 2. Per-tool call cap: max 3 calls of the same tool per turn
    local name_count=0
    name_count=$(echo "$TURN_CALLS" | tr ' ' '\n' | grep -c "^${name}_" 2>/dev/null) || name_count=0
    if [[ $name_count -ge 3 ]]; then
        echo "Error: You have already called '$name' ${name_count} times this turn. Do not retry further — answer using what you already have."
        return
    fi

    # We use a turn-scoped variable to track calls
    if [[ "$TURN_CALLS" == *"$call_sig"* ]]; then
        echo "Error: Loop detected! You already called $name with these exact arguments. Do not retry — answer using what you already have."
        return
    fi
    TURN_CALLS="$TURN_CALLS $call_sig"

    # Update Telegram status (HTML mode)
    tg_edit "$chat_id" "$msg_id" "⚒ Running tool: <code>$name</code>..." "HTML" > /dev/null
    
    log_tool_usage "$chat_id" "$name"
    local output
    output=$(run_tool "$name" "$args" "$chat_id" "$thread_id")

    # Check for image attachment
    if echo "$output" | grep -q "IMAGE_URL:"; then
        local img_url
        img_url=$(echo "$output" | grep "IMAGE_URL:" | head -n1 | sed 's/IMAGE_URL: //')
        tg_send_photo "$chat_id" "$img_url" "Generated by $name" > /dev/null
        output=$(echo "$output" | grep -v "IMAGE_URL:")
    fi

    # Return output — the agent loop handles the final Telegram message
    echo "$output"
}
